author: Damian Giebas
name: setup-env-common-steps
description: Common steps for jobs
inputs:
  python-version:
    description: Python version
    default: "3.11"
    required: false
  poetry-version:
    description: Poetry version
    default: "1.7.1"
    required: false
  working-directory:
    description: Working directory
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.python-version }}
  - name: Setup poetry
    uses: Gr1N/setup-poetry@v8
    with:
      python-version: ${{ inputs.python-version }}
      poetry-version: ${{ inputs.poetry-version }}
  - name: Install dependencies
    shell: bash
    run: cd ${{ inputs.working-directory }} && make install-dependencies
