name: Deploy pipeline
run-name: ${{ github.triggering_actor }} launched deploy via ${{ github.event_name }} on ${{ github.ref_name }}
on:
  push:
    branches:
    - "develop"
    - "master"
    tags:
    - "v*"

permissions:
  contents: read

jobs:
  build-aws-echo-lambda:
    name: Build and deploy aws-echo-lambda
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup-env
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    - run: make generate-aws-echo-lambda-deps
    - name: Upload requirements.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: requirements
        path: requirements.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: make build-aws-echo-lambda

    - name: Create image tag from tag ${{ github.ref_name }}
      if: startsWith(github.ref, 'refs/tags/v')
      run: make tag-aws-echo-lambda TAG=${{ github.ref_name }}

    - name: Create image tag from master branch
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      run: make tag-aws-echo-lambda TAG=latest

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-image-name:latest